### ISSUE TITLE
Make types work

### ISSUE THREAD

**Issue by sheremet-va** [Aslemammad/tinyspy#1]
We have an issue with `spyOn` types

It should have types with the description:

- if methodName is string, then treat obj[methodName] as function and return Spy<Arguments, ReturnType>
- if methodName is object { getter: keyof obj }, then treat obj[methodName.getter] as the getter and return Spy<[], GetterType>
- if methodName is object { setter: keyof obj }, then treat obj[methodName.setter] as the setter and return Spy<GetterArgs, []>

**Comment by tony-go** [comment]
Hi 👋 

Is what you are expecting for the first case:
<img width="412" alt="Screenshot 2021-12-13 at 14 37 41" src="https://user-images.githubusercontent.com/22824417/145822458-b971e7b3-724a-4d82-b5ac-821f0a75b0dc.png">

**Comment by sheremet-va** [comment]
Hey! Yes, that's it

**Comment by tony-go** [comment]
Progression:


- [x] if methodName is string, then treat obj[methodName] as function and return Spy<Arguments, ReturnType>
- [ ] if methodName is object { getter: keyof obj }, then treat obj[methodName.getter] as the getter and return Spy<[], GetterType>
- [ ] if methodName is object { setter: keyof obj }, then treat obj[methodName.setter] as the setter and return Spy<GetterArgs, []>
