### ISSUE TITLE
lint-staged -> nano-staged

### ISSUE THREAD

**Issue by usmanyunusov** [Aslemammad/tinyspy#10]
Would you like to use the minimalist analog of nano-staged instead of lint-staged? 
https://github.com/usmanyunusov/nano-staged

**Comment by Aslemammad** [comment]
Sure, why not!
Can you send a PR? also to https://github.com/Aslemammad/tinypool

**Comment by sheremet-va** [comment]
One of the main features of lint staged for us is clearing README before publishing
Does nano staged support it?

**Comment by usmanyunusov** [comment]
@sheremet-va 
This makes clean-publish. Could I be wrong?

**Comment by sheremet-va** [comment]
> @sheremet-va This makes [clean-publish](https://www.npmjs.com/package/clean-publish). Could I be wrong?

I'm sorry! I was wrong. Yes, clean publish does that.

**Comment by Aslemammad** [comment]
@usmanyunusov Feel free to send a PR, after this, could you also send one to `tinypool`?

**Comment by usmanyunusov** [comment]
https://github.com/Aslemammad/tinyspy/pull/12
