### ISSUE TITLE
Add asserts before mocking

### ISSUE THREAD

**Issue by sheremet-va** [Aslemammad/tinyspy#3]
If you are new to stubbing it's hard to find if you get an error or when something is not working as it should, so I think we should prevent these user mistakes by throwing errors before creating a mock

Example from jest spyOn
https://github.com/facebook/jest/blob/main/packages/jest-mock/src/index.ts#L1091

I think the most byteless method would be to create a wrapper

```ts
function assert(assertion: boolean, message: string) {
   if(!assertion)
      throw new Error(message)
}

assert(descriptor.configurable, `${propertyName} is not declared configurable`)
```

**Comment by Aslemammad** [comment]
i'm working on this.
